name: Audit

on:
  push:
  pull_request:
    types:
      - opened
jobs:
  Audit:
    name: 'Pull Request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: 'Use jq'
        uses: sergeysova/jq-action@v2

      - name: Install dependencies
        run: |-
          rm -rf node_modules
          yarn install

      - name: Do Audit
        run: |-
          set +e
          yarn audit --json --level high | jq -c '.[]' > ./AUDIO_OUTPUT
          set -e

      - name: Create vulnerability issue report
        uses: peter-evans/create-issue-from-file@v4
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          issue-number: PR- $PR_NUMBER
          token: ${{ secrets.GITHUB_TOKEN }}
          title: PR - $PR_NUMBER
          content-filepath: ./AUDIO_OUTPUT
          labels: |
            vulnerability
            automated

      - name: Run Test
        run: echo run your test code
