name: Audit

on:
  push:
  pull_request:
    types:
      - opened
jobs:
  test:
    name: 'Pull Request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: |-
          rm -rf node_modules
          yarn install

      - name: Audit
        run: |-
          set +e
          yarn audit --level high > ./AUDIO_OUTPUT
          set -e

      - name: Create vulnerability issue report
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Dependency vulnerability
          content-filepath: ./AUDIO_OUTPUT
          labels: |
            dependency
            vulnerability issue
            automated

      - name: Run Test
        run: echo run your test code
