name: Audit

on:
  push:
  pull_request:
    types:
      - opened
jobs:
  test:
    name: 'Pull Request'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency
        run: |-
          rm -rf node_modules

      - name: Test
        run: echo Testing

      - name: audit
        run: |-
          yarn audit
